In [2]:
import numpy as np
list_ = [ '1' ,'2' ,'3', '4', '5' ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

### ANS:

- Yes, there is a difference between the data types of list_ and array_list. list_ is a list object, whereas array_list is a numpy array object.

In [3]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(f"The data type of list_ is {type(list_)}")
print(f"The data type of array_list is {type(array_list)}")


The data type of list_ is <class 'list'>
The data type of array_list is <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print("Data type of each element in list_:")
for element in list_:
    print(f"  {element}: {type(element)}")

print("Data type of each element in array_list:")
for element in array_list:
    print(f"  {element}: {type(element)}")


Data type of each element in list_:
  1: <class 'str'>
  2: <class 'str'>
  3: <class 'str'>
  4: <class 'str'>
  5: <class 'str'>
Data type of each element in array_list:
  1: <class 'numpy.str_'>
  2: <class 'numpy.str_'>
  3: <class 'numpy.str_'>
  4: <class 'numpy.str_'>
  5: <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

In [ ]:
array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. Consider the below code to answer further questions:

In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [6]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [7]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print("Data type of each element in list_:")
for element in list_:
    print(f"  {element}: {type(element)}")

print("Data type of each element in array_list:")
for element in array_list:
    print(f"  {element}: {type(element)}")

Data type of each element in list_:
  1: <class 'str'>
  2: <class 'str'>
  3: <class 'str'>
  4: <class 'str'>
  5: <class 'str'>
Data type of each element in array_list:
  1: <class 'numpy.str_'>
  2: <class 'numpy.str_'>
  3: <class 'numpy.str_'>
  4: <class 'numpy.str_'>
  5: <class 'numpy.str_'>


### Q4. Write a code to find the following characteristics of variable, num_array:
- (i) shape
- (ii) size

In [10]:
num_array.shape

(2, 3)

In [11]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
import numpy as np

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [19]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])